---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-summon
description: Install summon through ansible
tags:
  - ansible
  - ansible-role
  - summon
github:
  has_issues: true
  has_projects: false
  has_wiki: false
